config/routes.rb
Rails.application.routes.draw do
  resources :bounties do
    get 'apply', on: :collection
  end

  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations",
                  passwords: "admins/passwords" }

  root :to => "bounties#index"

end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
  has_many :attachments, dependent: :destroy

  validates_presence_of :bounty_url
  validates_presence_of :bounty_name
  validates_presence_of :email
  validates :email, uniqueness: true, on: :create
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  mount_uploader :bounty_graphic, AvatarUploader
  mount_uploader :btc_image, AvatarUploader

  def delete_attachment
    old_attachments = Attachment.find_by_bounty_id(self.id)
    old_attachments.delete unless old_attachments == nil
  end
  
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController

  layout 'bounties'

  before_action :authenticate_admin!
  before_action :set_bounty, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @bounties = Bounty.all.order("id ASC").page(params[:page])
    respond_with(@bounties)
  end

  def apply
    #binding.pry
    checked_bounties_id = params[:chk]
    status = params[:status]
    is_status = false
    is_status = true if status == 'Publish'
    for bounty_id in checked_bounties_id do
      bounty = Bounty.find(bounty_id)
      bounty.status = is_status
      bounty.save
    end
    if is_status
      flash[:notice] = "Selection(s) have been published."
    else
      flash[:notice] = "Selection(s) have been privated."
    end
    redirect_to bounties_path
  end

  def show
    respond_with(@bounty)
  end

  def new
    @bounty = Bounty.new
    respond_with(@bounty)
  end

  def edit
    @starting_date = @bounty[:starting_date].strftime("%e %b %Y") unless @bounty[:starting_date] == nil
    @ending_date = @bounty[:ending_date].strftime("%e %b %Y") unless @bounty[:ending_date] == nil
    @attachments = Attachment.find_by_bounty_id(@bounty.id)
    binding.pry
  end

  def create
    @bounty = Bounty.new(bounty_params)

    #binding.pry
    @bounty[:starting_date] = params[:starting_date]
    @bounty[:ending_date] = params[:ending_date]

    if @bounty.save
      save_attachment @bounty
      redirect_to bounties_path, flash:{ :notice => "Created successfully."}
    else
      render :edit
    end
    #respond_with(@bounty)
  end

  def update
    #binding.pry
    if @bounty.update_attributes(bounty_params)
      attachment_title_list = params[:attachment_title]
      attachment_file_list = params[:attachment_file]
      is_changed_attachment = false
      for i in 0..attachment_title_list.length - 1
        if attachment_title_list[i] != "" and attachment_file_list[i] != ""
          is_changed_attachment = true
        end
      end
      
      if is_changed_attachment
        @bounty.delete_attachment
        save_attachment @bounty
      end
      
      redirect_to bounties_path, flash:{ :notice => "Updated successfully."}
    else
      render :edit
    end
    
    #respond_with(@bounty)
  end

  def save_attachment bounty
    attachment_title_list = params[:attachment_title]
    attachment_file_list = params[:attachment_file]
    for i in 0..attachment_title_list.length - 1
      if attachment_title_list[i] != "" and attachment_file_list[i] != ""
        attachment = Attachment.new({:bounty_id => bounty.id, :title => attachment_title_list[i], :address => attachment_file_list[i]})
        attachment.save
      end
    end
  end



  def destroy
    @bounty.destroy
    redirect_to bounties_path, flash:{ :notice => "Deleted successfully."}
  end

  private
    def set_bounty
      @bounty = Bounty.find(params[:id])
    end

    def bounty_params
      #params[:bounty]
      params.require(:bounty).permit([:bounty_title, :bounty_url, :status, :convicted, :progress, :bounty_graphic, 
                                        :bounty_name, :email, :short_desc, :summary, 
                                        :background, :btc_address, :discussion, :remote_btc_image_url])
    end
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/views/bounties/_form.html.haml
= form_for(@bounty) do |f|
  - if @bounty.errors.any?
    #error_explanation
      %h2
        = pluralize(@bounty.errors.count, "error")
        prohibited this bounty from being saved:
      %ul
        - @bounty.errors.full_messages.each do |message|
          %li= message
  %p
    = label_tag 'status', 'Status'
    /= select_tag "status", options_for_select(["Published", "Private"], "Published")
    = f.select 'status', [["Published", true], ["Private", false]]
  %p
    = label_tag 'bounty_title', 'Bounty Title:'
    %br
    = f.text_field "bounty_title", class: "text", size: "60"
  %p
    = label_tag 'bounty_url', 'URL:'
    %br
    = f.text_field "bounty_url", class: "text", size: "60"
  %p
    = label_tag 'convicted', 'Convicted'
    = f.select 'convicted', [["True", true], ["False", false]]
  %p
    = label_tag 'progress', 'Progress'
    = f.select 'progress', [["True", true], ["False", false]]
  %p.fileupload
    = label_tag 'bounty_graphic', 'Bounty Graphic'
    %br
    = f.file_field 'bounty_graphic'
  %p
    = label_tag 'bounty_name', "Name:"
    %br
    = f.text_field "bounty_name", class: "text", size: "60"
  %p
    = label_tag 'email', "User's Email:"
    %br
    = f.text_field "email", class: "text", size: "60"
  %p
    = label_tag 'short_desc', "Short Description(One line):"
    %br
    = f.text_field "short_desc", class: "text", size: "100"
  %p
    = label_tag 'summary', 'Summary:'
    %br/
    = f.text_area 'summary', class: 'wysiwyg', cols: "100"
  %p
    = label_tag 'background', 'Background:'
    %br/
    = f.text_area 'background', class: 'wysiwyg', cols: "100"
  %br/
  %p
    = label_tag 'starting_date', 'Starting date:'
    = text_field_tag 'starting_date', nil, class: 'text date_picker', type:'text', value: @starting_date
    \&nbsp;&nbsp;
    = label_tag 'ending_date', 'Ending date:'
    = text_field_tag 'ending_date', nil, class: 'text date_picker', type:'text', value: @ending_date
  %br/
  #attachment
    %p.fileupload
      %label Attachment Title:
      %br/
      = text_field_tag 'attachment_title[]', nil, class: 'text', type: 'text', size: '60'
      %br
      %br
      = file_field_tag 'attachment_file[]', class: 'file'
    %p.fileupload
      %label Attachment Title:
      %br/
      = text_field_tag 'attachment_title[]', nil, class: 'text', type: 'text', size: '60'
      %br
      %br
      = file_field_tag 'attachment_file[]', class: 'file'
  %p
    = link_to 'Add another attachment', nil, class: "add_attachment"
  %p
    %label BTC Address:
    %br/
    = f.text_field 'btc_address', type: 'text', size: '60', class: 'text'
    = f.text_field :remote_btc_image_url, type:'hidden'
  %p
    %label Discussion:
    %br/
    = f.text_field 'discussion', type: 'text', size: '60', class: 'text'
  %p
    - if @bounty.new_record?
      %input.submit{:type => "submit", :value => "Create"}/
    - else
      %input.submit{:type => "submit", :value => "Save"}/

app/views/bounties/edit.html.haml
%section#content
  .breadcrumb
  %h2 Edit a bounty
  = render 'form'
  = link_to 'Show', @bounty
  |
  \#{link_to 'Back', bounties_path}

app/views/bounties/index.html.haml
%section#content
  .breadcrumb
  / .breadcrumb ends
  %h2 List of Bounties
  %div{:style => "padding-bottom: 10px;"}
    = link_to 'New Bounty', new_bounty_path
  = form_tag apply_bounties_path, method: :get do
    %table.sortable{:cellpadding => "0", :cellspacing => "0", :width => "100%"}
      = render 'shared/bounties_message'
      %thead
        %tr
          %th{:width => "10"}
            %input.check_all{:type => "checkbox"}/
          %th Bounty title
          %th Status
          %th Convicted
          %th Last Date
          %th Bounty
          %th &nbsp;
      %tbody
        - @bounties.each do |bounty|
          %tr
            %td
              /%input{:type => "checkbox", :name => "chk"}
              = check_box_tag('chk[]', bounty.id)
              %input{:type => "hidden", :value => "#{bounty.id}"}
            %td
              %strong
                = link_to bounty.bounty_title, edit_bounty_path(bounty)
            %td
              - if bounty.status == true
                Published
              - else
                Private
            %td
              = bounty.convicted
            %td
              = bounty.updated_at.strftime("%m.%d.%Y")
            %td
              %a{:href => "#"}
                %div{"data-btcaddress" => "187Udd14Eqmfm4oAtEhSvau7kmasXn2e4j", "data-btcbalance" => "true"} Loading...
            %td.delete
              %a{"data-confirm" => "Are you sure to want to delete this bounty?", "data-method" => "delete", :href => bounty_path(bounty), :rel => "nofollow"}
                %img{:alt => "Delete", :src => "/assets/close.png", :title => "Delete"}/
              
              
        
    .tableactions
      = select_tag "status", options_for_select([ "Private", "Publish"], "Private")
      %input.submit.tiny{:type => "submit", :value => "Apply to selected", :onclick => "return btnApplyClick();"}/
    .table_pagination.right
      = paginate @bounties
    
      
  %br/
  %br/
  %hr/
  %br/
/ #content ends

app/views/bounties/new.html.haml
%section#content
  .breadcrumb
  %h2 Create a Bounty
  = render 'form'
  = link_to 'Back', bounties_path

app/views/bounties/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bounty_path(@bounty) %> |
<%= link_to 'Back', bounties_path %>