config/routes.rb
Rails.application.routes.draw do
  resources :bounties do
    get 'apply', on: :collection
  end

  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations",
                  passwords: "admins/passwords" }

  root :to => "bounties#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BountyHunterAdmin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = render "shared/flashes"
      %p
        - if admin_signed_in?
          /= current_admin.email
          = link_to "Sign Out", destroy_admin_session_path, method: :delete
    = yield

app/views/layouts/bounties.html.haml
!!!
%html
  %head
    %title BountyHunterAdmin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      %h1
        %a{:href => "page.html"} Bitcoin Bounty
      %section.userprofile
        %ul
          %li
            %a{:href => "#"}
              %img{:alt => "", :src => "/assets/avatar.gif"}/
              = current_admin.email
            %ul
              / %li
              /   %a{:href => "#"} Profile
              %li
                = link_to "Sign Out", destroy_admin_session_path, method: :delete
    %aside
      %ul#nav
        %li
          = link_to bounties_path do
            %strong
              %img{:alt => "", :src => "/assets/nav/pages.png"}/
              Bounties
        
    = yield

app/views/layouts/login.html.haml
!!!
%html
  %head
    %title BountyHunterAdmin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.loginpage
    %section#content.loginbox
      = render 'shared/login_message'
      = yield